version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./.dockerdev/node/Dockerfile
      args:
        NODE_VERSION: '14'
    image: campusreel-dev:1.0.0
    command: npm run start
    ports:
      - '5000:5000'
    volumes:
      - .:/app:cached
    environment:
      - NODE_ENV=development
      - WEB_CONCURRENCY=1
    depends_on:
      - postgres
  postgres:
    image: postgres:11.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '54320:5432'
  angular:
    build:
      context: .
      dockerfile: ./.dockerdev/angular/Dockerfile
    command: yarn run start
    ports:
      - '4200:4200'
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=${NODE_ENV:-development}

volumes:
  postgres:
